Update Makefile
Changing assignment due to:
```
Run make WORKFLOW_ID=escalation \
  make WORKFLOW_ID=escalation \
    APPLICATION_ID=jira-listener \
    GIT_TOKEN=*** \
    REGISTRY_REPO=orchestrator \
    REGISTRY_USERNAME=*** \
    REGISTRY_PASSWORD=*** \
    build-image push-image
  shell: /usr/bin/bash -e {0}
  env:
    DEPLOYMENT_REPO: parodos-dev/serverless-workflows-config
    REGISTRY_REPO: orchestrator
    GH_TOKEN: ***
    REGISTRY_AUTH_FILE: /run/user/1001/containers/auth.json
Preparing workdir /tmp/tmp.CJtGVCDFBd
Building quay.io/orchestrator/serverless-workflow-jira-listener
# First build the application
scripts/build_application.sh podman /tmp/tmp.aBNKmA0xyY escalation jira-listener registry.access.redhat.com/ubi9/openjdk-17:1.17 -B
scripts/build_application.sh: line 10: cd: /tmp/tmp.aBNKmA0xyY/escalation/jira-listener: No such file or directory
make: *** [Makefile:106: build-image] Error 1
Error: Process completed with exit code 2.
```
from https://github.com/parodos-dev/serverless-workflows/actions/runs/8437990944/job/23109073193